export enum Language {
    BR,
    EN
  }

export enum LanguageText {
    COST_TOTAL,
    POWER_UP_AUTOMATION,
    POWER_UP_CI_CD,
    POWER_UP_NEW_DEV,
    POWER_UP_NEW_PO,
    POWER_UP_NEW_QA,
    POWER_UP_TRAIN_DEV_TO_ACTION_PO,
    POWER_UP_TRAIN_DEV_TO_ACTION_QA,
    POWER_UP_TRAIN_PO_TO_ACTION_QA,
    POWER_UP_TRAIN_PO_TO_ACTION_DEV,
    POWER_UP_TRAIN_QA_TO_ACTION_PO,
    POWER_UP_TRAIN_QA_TO_ACTION_DEV,
    POWER_UP_AUTOMATION_DESCRIPTION,
    POWER_UP_CI_CD_DESCRIPTION,
    POWER_UP_NEW_DEV_DESCRIPTION,
    POWER_UP_NEW_PO_DESCRIPTION,
    POWER_UP_NEW_QA_DESCRIPTION,
    POWER_UP_TRAIN_DEV_TO_ACTION_PO_DESCRIPTION,
    POWER_UP_TRAIN_DEV_TO_ACTION_QA_DESCRIPTION,
    POWER_UP_TRAIN_PO_TO_ACTION_QA_DESCRIPTION,
    POWER_UP_TRAIN_PO_TO_ACTION_DEV_DESCRIPTION,
    POWER_UP_TRAIN_QA_TO_ACTION_PO_DESCRIPTION,
    POWER_UP_TRAIN_QA_TO_ACTION_DEV_DESCRIPTION,
    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SHOP,
    ROUND,
    NEXT_ROUND,
    DEPLOY_DAY,
    BACKLOG,
    IN_ANALYSIS,
    IN_DEVELOPMENT,
    IN_TESTS,
    WAITING_DEPLOY,
    IN_PRODUCTION,
    DONE,
    RESET_BOARD,
    RESET_BOARD_DESCRIPTION,
    EMPLOYEES,
    PROJECTS,
    TASKS,
    SHOP_DAY,
    ERROR_EMPLOYEE_ACTION_WRONG,
    ERROR_CARD_MOVE_DEVELOPER_WRONG,
    ERROR_CARD_MOVE_TEST_WRONG,
    ERROR_CARD_MOVE_DEPLOY_WRONG,
    ERROR_CARD_MOVE_BACK_PRODUCTION,
    ERROR_CARD_PRODUCTION_NO_EMPLOYEE,
    ERROR_CARD_PRODUCTION_NO_DAY,
    ERROR_CARD_PONTUATION_MOVED_THIS_ROUND,
    ERROR_CARD_PONTUATION_COLUMN_WRONG,
    ERROR_CARD_PONTUATION_MAX_PONTUATION,
    ERROR_CARD_PONTUATION_NEED_ANALYSIS,
    ERROR_CARD_PONTUATION_NEED_DEVELOPMENT,
    ERROR_CARD_PONTUATION_NO_HAVE_POINT,
    ERROR_PROJECT_CANNOT_MOVE_TO_BACK,
    ERROR_PROJECT_NOT_DONE,
    POWER_UP_AUTOMATION_INFO_FINISH,
    POWER_UP_CI_CD_INFO_FINISH,
    POWER_UP_GENERIC_INFO_FINISH,
    ARCHIVED,
    MADE_WITH_LOVE
}

export type LanguageResult = {
    br: string,
    en: string
}

const textMap = new Map<LanguageText, LanguageResult>([
    [LanguageText.COST_TOTAL, {br: 'Custo atual do projeto: $', en: 'Actual cost of project: $'}],
    [LanguageText.POWER_UP_AUTOMATION_INFO_FINISH, {br: 'Agora você não precisa alocar um desenvolvedor para fazer deploy.', en: 'Now you dont need allocate a developer to make deploy.'}],
    [LanguageText.POWER_UP_CI_CD_INFO_FINISH, {br: 'Agora você pode fazer deploy todos os dias da semana', en: 'Now you can make deploy every day.'}],
    [LanguageText.POWER_UP_GENERIC_INFO_FINISH, {br: 'Você finalizou uma tarefa de melhoria.', en: 'You finish a power up task.'}],
    [LanguageText.POWER_UP_AUTOMATION, {br: 'Automação', en: 'Automation'}],
    [LanguageText.POWER_UP_CI_CD, {br: 'Entrega contínua', en: 'Continuos Delivery'}],
    [LanguageText.POWER_UP_NEW_DEV, {br: 'Contratar DEV', en: 'To hire DEV'}],
    [LanguageText.POWER_UP_NEW_PO, {br: 'Contratar PO', en: 'To hire PO'}],
    [LanguageText.POWER_UP_NEW_QA, {br: 'Contratar QA', en: 'To hire QA'}],
    [LanguageText.POWER_UP_TRAIN_DEV_TO_ACTION_PO, {br: 'Treinar DEV como PO', en: 'Train DEV like PO'}],
    [LanguageText.POWER_UP_TRAIN_DEV_TO_ACTION_QA, {br: 'Treinar DEV como QA', en: 'Train DEV like QA'}],
    [LanguageText.POWER_UP_TRAIN_PO_TO_ACTION_QA, {br: 'Treinar PO como QA', en: 'Train PO like QA'}],
    [LanguageText.POWER_UP_TRAIN_PO_TO_ACTION_DEV, {br: 'Treinar PO como DEV', en: 'Train PO like DEV'}],
    [LanguageText.POWER_UP_TRAIN_QA_TO_ACTION_PO, {br: 'Treinar QA como PO', en: 'Train QA like PO'}],
    [LanguageText.POWER_UP_TRAIN_QA_TO_ACTION_DEV, {br: 'Treinar QA como DEV', en: 'Train QA like DEV'}],
    [LanguageText.POWER_UP_AUTOMATION_DESCRIPTION, {br: 'Ao comprar essa melhoria você automatiza seu processo.', en: 'With this improvement you automate your process.'}],
    [LanguageText.POWER_UP_CI_CD_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá realizar integrações contínuas.', en: 'With this improvement you will be performing continuous integrations.'}],
    [LanguageText.POWER_UP_NEW_DEV_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá contratar um novo desenvolvedor.', en: 'With this improvement you will hire a new developer'}],
    [LanguageText.POWER_UP_NEW_PO_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá contratar um novo product owner.', en: 'With this improvement you will hire a new product owner'}],
    [LanguageText.POWER_UP_NEW_QA_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá contratar um novo quality assurance.', en: 'With this improvement you will hire a new quality assurance'}],
    [LanguageText.POWER_UP_TRAIN_DEV_TO_ACTION_PO_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um desenvolvedor para atuar como product owner.', en: 'You will train a developer to act as a product owner.'}],
    [LanguageText.POWER_UP_TRAIN_DEV_TO_ACTION_QA_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um desenvolvedor para atuar como quality assurance.', en: 'You will train a developer to act as a quality assurance.'}],
    [LanguageText.POWER_UP_TRAIN_PO_TO_ACTION_QA_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um product owner para atuar como quality assurance.', en: 'You will train a product owner to act as a quality assurance.'}],
    [LanguageText.POWER_UP_TRAIN_PO_TO_ACTION_DEV_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um product owner para atuar como desenvolvedor.', en: 'You will train a product owner to act as a developer.'}],
    [LanguageText.POWER_UP_TRAIN_QA_TO_ACTION_PO_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um quality assurance para atuar como product owner.', en: 'You will train a quality assurance to act as a developer.'}],
    [LanguageText.POWER_UP_TRAIN_QA_TO_ACTION_DEV_DESCRIPTION, {br: 'Ao comprar essa melhoria você irá treinar um quality assurance para atuar como desenvolvedor.', en: 'You will train a quality assurance to act as a product owner.'}],
    [LanguageText.MONDAY, {br: 'Segunda-feira', en: 'Monday'}],
    [LanguageText.TUESDAY, {br: 'Terça-feira', en: 'Tuesday'}],
    [LanguageText.WEDNESDAY, {br: 'Quarta-feira', en: 'Wednesday'}],
    [LanguageText.THURSDAY, {br: 'Quinta-feira', en: 'Thursday'}],
    [LanguageText.FRIDAY, {br: 'Sexta-feira', en: 'Friday'}],
    [LanguageText.SHOP, {br: 'LOJA', en: 'STORE'}],
    [LanguageText.ROUND, {br: 'RODADA', en: 'ROUND'}],
    [LanguageText.NEXT_ROUND, {br: 'PRÓXIMA RODADA', en: 'NEXT ROUND'}],
    [LanguageText.DEPLOY_DAY, {br: 'Dia de Deploy', en: 'Deploy day'}],
    [LanguageText.BACKLOG, {br: 'A fazer', en: 'Backlog'}],
    [LanguageText.IN_ANALYSIS, {br: 'Em análise', en: 'In analysis'}],
    [LanguageText.IN_DEVELOPMENT, {br: 'Em desenvolvimento', en: 'Development'}],
    [LanguageText.IN_TESTS, {br: 'Em testes', en: 'Test'}],
    [LanguageText.WAITING_DEPLOY, {br: 'Aguardando deploy', en: 'Waiting Deploy'}],
    [LanguageText.IN_PRODUCTION, {br: 'Em produção', en: 'Production'}],
    [LanguageText.DONE, {br: 'Pronto', en: 'Done'}],
    [LanguageText.RESET_BOARD, {br: 'Reiniciar jogo', en: 'Reset game'}],
    [LanguageText.RESET_BOARD_DESCRIPTION, {br: 'Todo o seu progresso será perdido, você tem certeza que deseja reiniciar o jogo?', en: 'Your progress will be lost, are you sure to restart the game?'}],
    [LanguageText.EMPLOYEES, {br: 'EQUIPE', en: 'TEAM'}],
    [LanguageText.PROJECTS, {br: 'PROJETOS', en: 'PROJECTS'}],
    [LanguageText.TASKS, {br: 'TAREFAS', en: 'TASKS'}],
    [LanguageText.ARCHIVED, {br: 'Tarefas Arquivadas', en: 'Tasks Archiveds'}],
    [LanguageText.SHOP_DAY, {br: 'A loja está aberta', en: 'Store is open'}],
    [LanguageText.ERROR_EMPLOYEE_ACTION_WRONG, {br: 'Esse funcionário não consegue relizar essa função.', en: 'This employee cannot perform this function.'}],
    [LanguageText.ERROR_CARD_MOVE_DEVELOPER_WRONG, {br: 'Não é possível mover para desenvolvimento.', en: 'Cannot move to development.'}],
    [LanguageText.ERROR_CARD_MOVE_TEST_WRONG, {br: 'Não é possível mover para testes.', en: 'Cannot move to tests.'}],
    [LanguageText.ERROR_CARD_MOVE_DEPLOY_WRONG, {br: 'Não é possível mover para deploy.', en: 'Cannot move to deploy.'}],
    [LanguageText.ERROR_CARD_MOVE_BACK_PRODUCTION, {br: 'Não pode voltar de produção.', en: 'Cannot move back of production.'}],
    [LanguageText.ERROR_CARD_PRODUCTION_NO_DAY, {br: 'Não é possível mover para produção hoje.', en: 'Cannot move to production today.'}],
    [LanguageText.ERROR_CARD_PRODUCTION_NO_EMPLOYEE, {br: 'Não é possível realizar o deploy, por que não foi alocado um funcionário para essa função.', en: 'Cannot move to deploy, because no employee was allocated for this function.'}],
    [LanguageText.ERROR_CARD_PONTUATION_MOVED_THIS_ROUND, {br: 'Não é possível pontuar em uma tarefa que acabou de ser movida.', en: 'Cannot spend point on this card as it was moved this round.'}],
    [LanguageText.ERROR_CARD_PONTUATION_COLUMN_WRONG, {br: 'Não é possível utilizar nesta coluna.', en: 'Cannot spend point in this column.'}],
    [LanguageText.ERROR_CARD_PONTUATION_MAX_PONTUATION, {br: 'O máximo de pontuação já foi utilizado.', en: 'Max points was been alcanced.'}],
    [LanguageText.ERROR_CARD_PONTUATION_NEED_DEVELOPMENT, {br: 'Necessário realizar o desenvolvimento', en: 'Need to carry out the development.'}],
    [LanguageText.ERROR_CARD_PONTUATION_NEED_ANALYSIS, {br: 'Necessário realizar a análise.', en: 'Need to carry out the analysis.'}],
    [LanguageText.ERROR_CARD_PONTUATION_NO_HAVE_POINT, {br: 'Não há pontos suficientes para utilizar.', en: 'No have points to use.'}],
    [LanguageText.ERROR_PROJECT_CANNOT_MOVE_TO_BACK, {br: 'Projeto não pode ser movido para trás.', en: 'Cannot move project to back.'}],
    [LanguageText.ERROR_PROJECT_NOT_DONE, {br: 'Não é possível mover para testes.', en: 'Projet is not done.'}],
    [LanguageText.MADE_WITH_LOVE, {br: 'Feito com ❤️ por Julio Cruz', en: 'Made with ❤️ by Julio Cruz'}],
]);

export function getText(text: LanguageText, language: Language): string {
    const result = textMap.get(text)!
    if(language == Language.BR) return result.br
    return result.en
}